# Generated by Django 5.1.7 on 2025-03-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
